In [75]:
import numpy as np


In [76]:
A=np.array([3,4,5,6])
print(A)

[3 4 5 6]


In [77]:
B=np.array([(2,4,5,70),(94,5,6,3)], dtype=float)
print(B)

[[ 2.  4.  5. 70.]
 [94.  5.  6.  3.]]


In [78]:
np.zeros((4,5))  #Create an array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
np.ones((2,3,6),dtype=np.int64)   #Create an array of ones

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int64)

In [80]:
np.arange(25, 50,5)             ## Create an array of evenly spaced values (step value) 

array([25, 30, 35, 40, 45])

In [81]:
np.linspace(3,6,5)    #Create an array of evenly spaced values (number of samples)

array([3.  , 3.75, 4.5 , 5.25, 6.  ])

In [82]:
np.full((3,5),8)    # Create a constant array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [83]:
np.eye(4)      #Create a 2X2 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [152]:
np.empty((2,6))       #Create an empty array

array([[8.29511426e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 4.47032019e-038],
       [5.58769867e-091, 1.53404710e-075, 4.31983632e-038,
        1.12983193e-042, 3.99910963e+252, 5.82471487e+257]])

In [85]:
np.random.random((5,5))    #Create an array with random values

array([[0.23804742, 0.49524621, 0.00101303, 0.1712155 , 0.36445478],
       [0.03180401, 0.08312222, 0.55795751, 0.07554252, 0.10658902],
       [0.15049364, 0.09510766, 0.43395252, 0.92143247, 0.48973891],
       [0.54161214, 0.96554018, 0.71070104, 0.94755594, 0.54160963],
       [0.60205397, 0.09587646, 0.01642548, 0.54507543, 0.52542772]])

In [86]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [87]:
A.shape #Array dimensions

(4,)

In [88]:
A.ndim    #Number of array dimensions

1

In [89]:
len(A)       #Length of array

4

In [90]:
A.size          #Number of array elements

4

In [91]:
A.dtype            #Data type of array elements

dtype('int32')

In [92]:
A.astype(float)     #Convert an array to a different type

array([3., 4., 5., 6.])

In [93]:
G=A-B    #Subtraction
print(G)

[[  1.   0.   0. -64.]
 [-91.  -1.  -1.   3.]]


In [94]:
np.subtract(A,B)    #Subtraction

array([[  1.,   0.,   0., -64.],
       [-91.,  -1.,  -1.,   3.]])

In [95]:
A+B    #Addition

array([[ 5.,  8., 10., 76.],
       [97.,  9., 11.,  9.]])

In [96]:
np.add(A,B)                  #Addition

array([[ 5.,  8., 10., 76.],
       [97.,  9., 11.,  9.]])

In [97]:
A/B                         #Division

array([[1.5       , 1.        , 1.        , 0.08571429],
       [0.03191489, 0.8       , 0.83333333, 2.        ]])

In [98]:
np.divide(A,B)                #Division

array([[1.5       , 1.        , 1.        , 0.08571429],
       [0.03191489, 0.8       , 0.83333333, 2.        ]])

In [99]:
A*B                           #Multiplication

array([[  6.,  16.,  25., 420.],
       [282.,  20.,  30.,  18.]])

In [100]:
np.multiply(A,B)                    #Multipilication

array([[  6.,  16.,  25., 420.],
       [282.,  20.,  30.,  18.]])

In [101]:
np.exp(B)                                #Exponentiation

array([[7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 2.51543867e+30],
       [6.66317622e+40, 1.48413159e+02, 4.03428793e+02, 2.00855369e+01]])

In [102]:
np.sqrt(B)                         #Square root

array([[1.41421356, 2.        , 2.23606798, 8.36660027],
       [9.69535971, 2.23606798, 2.44948974, 1.73205081]])

In [103]:
np.sin(B)                          #Print sines of an array

array([[ 0.90929743, -0.7568025 , -0.95892427,  0.77389068],
       [-0.24525199, -0.95892427, -0.2794155 ,  0.14112001]])

In [104]:
np.cos(B)                        #Element-wise cosine 

array([[-0.41614684, -0.65364362,  0.28366219,  0.6333192 ],
       [ 0.96945937,  0.28366219,  0.96017029, -0.9899925 ]])

In [105]:
np.log(B)                      #Element-wise natural logarithm

array([[0.69314718, 1.38629436, 1.60943791, 4.24849524],
       [4.54329478, 1.60943791, 1.79175947, 1.09861229]])

In [106]:
A==B      #Element wise comparison

array([[False,  True,  True, False],
       [False, False, False, False]])

In [107]:
B > 3    #Element-wise comparison

array([[False,  True,  True,  True],
       [ True,  True,  True, False]])

In [108]:
np.array_equal(A, B) #Array-wise comparison

False

In [109]:

A.sum() #Array-wise sum

18

In [110]:
A.max(axis=0) #Maximum value of an array row

6

In [111]:
B.min() #Array-wise minimum value

2.0

In [112]:
B.cumsum(axis=1) #Cumulative sum of the elements

array([[  2.,   6.,  11.,  81.],
       [ 94.,  99., 105., 108.]])

In [113]:
B.mean() #Mean

23.625

In [114]:
np.median(A) #Median

4.5

In [115]:
np.corrcoef(A) #Correlation coefficient

1.0

In [116]:
np.std(B) #Standard deviation

34.25250903218624

In [117]:
h = B.view()   #Create a view of the array with the same data
print(h)

[[ 2.  4.  5. 70.]
 [94.  5.  6.  3.]]


In [118]:
C=np.copy(B) #Create a copy of the array
print(C)

[[ 2.  4.  5. 70.]
 [94.  5.  6.  3.]]


In [119]:
f = A.copy() #Create a deep copy of the array
print(f)

[3 4 5 6]


In [120]:
A.sort()  #Sort an array

In [121]:
C.sort(axis=0)  #Sort the elements of an array's axis

In [122]:
A[3]   # Select the element at the 2nd index 3

6

In [123]:
B[1,3] #Select the element at row 1 column 2 (equivalent to b[1][2])

3.0

In [124]:
A[0:3]      #Select items at index 0 and 1

array([3, 4, 5])

In [125]:
B[0:3,2]     #Select items at rows 0 and 1 in column 1

array([5., 6.])

In [126]:
B[:3]      #Select all items at row 0 (equivalent to b[0:1, :])

array([[ 2.,  4.,  5., 70.],
       [94.,  5.,  6.,  3.]])

In [127]:
B[1,...]    #Same as [1,:,:]

array([94.,  5.,  6.,  3.])

In [128]:
B[ : :-1] #Reversed array a array([3, 2, 1])

array([[94.,  5.,  6.,  3.],
       [ 2.,  4.,  5., 70.]])

In [129]:
B[[1, 0, 0, 0],[0, 1, 3, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)

array([94.,  4., 70.,  2.])

In [130]:
B[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns

array([[94.,  5.,  6., 94.],
       [ 2.,  4.,  5.,  2.],
       [94.,  5.,  6., 94.],
       [ 2.,  4.,  5.,  2.]])

In [131]:
i = np.transpose(B)          #Permute array dimension
print(i)

[[ 2. 94.]
 [ 4.  5.]
 [ 5.  6.]
 [70.  3.]]


In [132]:
i.T                          #Permute array dimensions

array([[ 2.,  4.,  5., 70.],
       [94.,  5.,  6.,  3.]])

In [133]:
B.ravel()                    #Flatten the array

array([ 2.,  4.,  5., 70., 94.,  5.,  6.,  3.])

In [134]:
G.reshape(4,-2)              #Reshape, but don’t change data

array([[  1.,   0.],
       [  0., -64.],
       [-91.,  -1.],
       [ -1.,   3.]])

In [135]:
f.resize((2,6))              #Return a new array with shape (2,6)

In [136]:
np.append(f,G)               #Append items to an array

array([  3.,   4.,   5.,   6.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   1.,   0.,   0., -64., -91.,  -1.,  -1.,   3.])

In [137]:
np.insert(A, 1, 5)           #Insert items in an array

array([3, 5, 4, 5, 6])

In [138]:
np.delete(B,[1])             #Delete items from an array

array([ 2.,  5., 70., 94.,  5.,  6.,  3.])

In [139]:
a=np.array([3,4,5,6])
b=np.array([3,2,5,8])

In [140]:
np.concatenate((a,b),axis=0) #Concatenate array      

array([3, 4, 5, 6, 3, 2, 5, 8])

In [141]:
np.vstack((a,b))             #Stack arrays vertically (row-wise)

array([[3, 4, 5, 6],
       [3, 2, 5, 8]])

In [142]:
np.r_[a,b]                   #Stack arrays vertically (row-wise)

array([3, 4, 5, 6, 3, 2, 5, 8])

In [143]:

np.hstack((a,b))             #Stack arrays horizontally (column-wise)

array([3, 4, 5, 6, 3, 2, 5, 8])

In [144]:
v=np.column_stack((a,b))       #Create stacked column-wise arrays
print(v)

[[3 3]
 [4 2]
 [5 5]
 [6 8]]


In [145]:
np.c_[a,b]                   #Create stacked column-wise arrays

array([[3, 3],
       [4, 2],
       [5, 5],
       [6, 8]])

In [146]:
np.hsplit(a,2)               #Split the array horizontally at the 3rd index

[array([3, 4]), array([5, 6])]

In [147]:
np.vsplit(v,2)               #Split the array vertically at the 2nd index

[array([[3, 3],
        [4, 2]]),
 array([[5, 5],
        [6, 8]])]